-- Intentionally empty. Creating a fixed administrator through auth.users is unsafe.
-- Create the first account in Supabase Authentication, then promote its profile as
-- described in README.md. Later accounts are managed from the application.